name: Vault OIDC Demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Generate JWT
        run: |

          echo "Generating GitHub JWT..."

          JWT=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=vault" \
            | jq -r '.value')

          echo "$JWT" > jwt-token.txt

          echo "JWT saved into jwt-token.txt"

      - name: Upload JWT Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jwt-token
          path: jwt-token.txt

          JWT=$(echo "$RESPONSE" | jq -r '.value')

          echo ""
          echo "JWT TOKEN:"
          echo "$JWT"
